= Chapter 2: Building Our First .NET MAUI App

:v-1.0.0: 2025-11-07 | Chapters 1, 2, and 1/3 of Chapter 3 only
:v-1.0.1: 2026-04-24 | up to 2026-04-27

(Note: for testing on Android, you just installed Android Studio, which is a recommended setup by James Montemagno in his video [see link below])

Font Awesome: https://github.com/FortAwesome/Font-Awesome


We can define font glyphs as C# string constants so that we can refer to something more meaningful. There are many ways to do this. Here, we use the open source tool IconFont2Code to generate string constants.
 - https://github.com/andreinitescu/IconFont2Code

Shell is supported by Microsoft.Maui.Controls.Shell and Xamarin.Forms.Shell in .NET MAUI and Xamarin.Forms. It provides a common navigation user experience that can be used on all platforms. We will explain more about Shell in Chapter 5, Introducing Shell and Navigation. We will use .NET MAUI Shell as the UI framework and navigation method in this book.



.NET MAUI MVVM App Template by Roger Ye: https://marketplace.visualstudio.com/items?itemName=shugaoye.maui


build and run for Android: `dotnet build -t:Run -f net6.0-android`

build and test the iOS target: `dotnet build -t:Run -f net6.0-ios -p:_
DeviceName=:v2:udid=02C556DA-64B8-440B-8F06-F8C56BB7CC22`

   To select a target iOS emulator, we need to provide the device ID using the following parameter: `-p:_DeviceName=:v2:udid=`

   To find the device ID, we can launch Xcode on a Mac computer and go to Windows -> Devices and Simulators,

For the macOS target: `dotnet build -t:Run -f net6.0-maccatalyst`

== Misc: Getting Started with MAUI in Visual Studio Code

https://www.youtube.com/watch?v=_SEStDLKHMc

Chapters:
00:00 - Introd
04:30 - Installing the .NET MAUI extension for VS Code
05:15 - Creating a new .NET MAUI app
06:45 - Using the C# Dev Kit extension
08:30 - Using the Get Started with .NET MAUI walkthrough
09:55 - Installing Xcode
10:35 - Installing Android SDKs and command line tools
13:15 - Setting startup project and debug targets
15:30 - Working with code
16:40 - Running and debugging the app
17:50 - Running the app on a simulator
19:25 - Discussion of Hot Reload
22:10 - Reporting an issue
22:55 - Wrap-up


== Misc: .NET MAUI Development in VS Code - Complete Setup Guide (Develop on macOS, Linux, & Windows)!

by James Montemagno

https://www.youtube.com/watch?v=1t2zzoW4D98

Chapters:
00:00 - Introduction
00:30 - Visual Studio vs VS Code Setup Comparison
01:40 - What you can developer where in VS Code
03:50 - Installing .NET and .NET MAUI Workload
08:40 - Installing VS Code and .NET MAUI Extensions
11:45 - Creating a .NET MAUI Project in VS Code
13:50 - Installing Xcode with Xcodes for iOS and Mac development

  `brew install --cask xcodes`

19:30 - Installing Android dependencies: JDK, Android Studio, & More
27:00 - Run & Debug iOS, Android, and Mac Applications from VS Code
30:20 - Wrap-up and final thoughts


== Error encountered: This version of .NET for MacCatalyst (26.2.10233) requires Xcode 26.3. The current version of Xcode is 26.4.1. Either install Xcode 26.3, or use a different version of .NET for MacCatalyst. See https://aka.ms/xcode-requirement for more information.

Solution: install Xcode version 26.3 using Xcodes or Xcodes CLI

`brew install xcodesorg/made/xcodes`
`xcodes list`
`xcodes install 26.3`
`xcodes select 26.3`
`xcodes installed`


== Error encountered: No simulator runtime version from ["23E254a"] available to use with iphonesimulator SDK version 23C57

Solution: Install iOS simulator for Xcode 26.3

1. Open Xcode 26.3 in Xcodes (GUI, not CLI)
2. Go to Settings -> Component
3. Then Install iOS simulator