= Chapter 9: Determining an Author's Message

:v-1.0.0: 2026-02-26 | 

== Quotes

Propositions are answers to questions. They are a declaration of knowledge or opinion.

**RULE 6: Mark the most important sentences in a book and discover the propositions they contain.**

**RULE 7: Locate or construct the basic arguments in the book by finding them in the connection of sentences.**

Wonder is the beginning of wisdom in learning from books as well as from nature.

(The fact that we have stated these rules in a fixed order does not mean that you have to follow them in that order.)

"State in your own words!"... if you cannot get away at all from the author's words, it shows that only words have passed from him to you, not thought or knowledge. You know his words, not his mind.

Propositions do not exist in a vacuum. They refer to the world in which we live.

**RULE 8: Find out what the author's solutions are.**

- RULE 8 ties together the first stage of analytical reading (outlining the structure) and the second stage (interpreting the contents).

== Recall / Retrieval 

Find out the propositions of the author --- those are the affirmations and denials he is making in the book. Then find out the arguments of the author --- those are the collection of proposition or sentences which are organized in a way as to form conclusions.


=== How to locate key sentences (p 121ff)

1. those which are difficult to understand
2. the author's affirmations and denials, and the reasons he gives for them
3. underlined or italicized sentences, formatted differently from the rest
4. those which contain the important words discovered using RULE 5 from Chapter 8
5. sentences which are premises or conclusions

=== How to know you have understood a proposition

1. state in your own words the proposition
2. give real-world examples, or imaginative examples, to illustrate the proposition